// 'use client'

// import React, { useContext, useEffect, useState } from 'react';
// import { Container, Typography, FormControl, InputLabel, Select, MenuItem, Button, Box, Card, CardContent, Input, List, ListItem, ListItemText, Divider } from '@mui/material';
// import { toast } from 'react-toastify';
// import userContext from '@/context/userDetails/UserContext';
// import QuestionPrototype from '@/app/components/QuestionPrototype';

// function CreateQuizPage() {
//     const context = useContext(userContext);
//     const { user } = context;
//     const [quizzes, setQuizzes] = useState([]);
//     const [selectedQuiz, setSelectedQuiz] = useState('');
//     const [quizName, setQuizName] = useState('');
    
//     // Manual Question State
//     const [manualType, setManualType] = useState('');
//     const [manualQuestion, setManualQuestion] = useState(null);

//     // AI Question State
//     const [aiQuestions, setAiQuestions] = useState([]);
    
//     const myID = user?._id;

//     useEffect(() => {
//         const fetchQuizzes = async () => {
//             try {
//                 const response = await fetch('/api/getquiz');
//                 if (!response.ok) throw new Error('Network response was not ok');
//                 const data = await response.json();
//                 setQuizzes(data);
//             } catch (error) {
//                 console.error('Failed to fetch quizzes:', error);
//             }
//         };
//         fetchQuizzes();
//     }, [myID]);

//     const handleCreateQuiz = async () => {
//         if (!quizName) {
//             toast.warning('Please provide a name for the quiz.');
//             return;
//         }
//         const response = await fetch('/api/quiz', {
//             method: 'POST',
//             headers: { 'Content-Type': 'application/json' },
//             body: JSON.stringify({ name: quizName, userId: myID }),
//         });
//         if (response.ok) {
//             const data = await response.json();
//             setQuizzes([...quizzes, data.quiz]);
//             setQuizName('');
//             toast.success("Quiz Created Successfully");
//         } else {
//             toast.warning('Failed to create quiz.');
//         }
//     };

//     const handleSelectManualType = (type) => {
//         setManualType(type);
//         setManualQuestion(
//             type === 'MCQs' ? { questionText: '', options: ['', '', '', ''], correctOption: 0 } :
//             type === 'True/False Questions' ? { questionText: '', correctOption: true } :
//             { questionText: '', correctAnswer: '' }
//         );
//     };

//     const handleSaveManual = async () => {
//         if (!selectedQuiz || !manualType || !manualQuestion) {
//             toast.error('Please select a quiz and enter question details.');
//             return;
//         }

//         const response = await fetch('/api/questions', {
//             method: 'POST',
//             headers: { 'Content-Type': 'application/json' },
//             body: JSON.stringify({ quizId: selectedQuiz, type: manualType, ...manualQuestion }),
//         });

//         if (response.ok) {
//             setManualQuestion(null);
//             setManualType('');
//             toast.success('Manual question saved successfully!');
//         } else {
//             toast.error('Failed to save manual question.');
//         }
//     };

//     const handleGenerateAI = async () => {
//         if (!selectedQuiz) {
//             toast.error('Please select a quiz first');
//             return;
//         }

//         const selectedQuizData = quizzes.find(q => q._id === selectedQuiz);
//         const inputText = selectedQuizData ? selectedQuizData.name : '';

//         toast.info("Generating 5 AI questions... please wait.");

//         const response = await fetch('/api/generate', {
//             method: 'POST',
//             headers: { 'Content-Type': 'application/json' },
//             body: JSON.stringify({ inputText, quizId: selectedQuiz }),
//         });

//         const result = await response.json();

//         if (response.ok) {
//             setAiQuestions(result.quizQuestions || []);
//             toast.success("5 Questions generated by AI!");
//         } else {
//             console.error('Failed to generate questions:', result.error);
//             toast.error('Failed to generate questions.');
//         }
//     };

//     const handleSaveAI = async () => {
//         if (!selectedQuiz || !aiQuestions.length) {
//             toast.error('No AI questions to save.');
//             return;
//         }

//         let successCount = 0;
//         for (let q of aiQuestions) {
//             const response = await fetch('/api/questions', {
//                 method: 'POST',
//                 headers: { 'Content-Type': 'application/json' },
//                 body: JSON.stringify({ quizId: selectedQuiz, ...q }),
//             });
//             if (response.ok) successCount++;
//         }

//         if (successCount === aiQuestions.length) {
//             toast.success(`Successfully saved all ${successCount} AI questions!`);
//             setAiQuestions([]);
//         } else {
//             toast.warning(`Saved ${successCount} out of ${aiQuestions.length} questions.`);
//         }
//     };

//     return (
//         <Container maxWidth="md" sx={{ py: 4 }}>
//             <Box display="flex" flexDirection="column" gap={4}>
//                 {/* Section 1: Create Quiz */}
//                 <Card sx={{ boxShadow: 3, borderRadius: 3 }}>
//                     <CardContent>
//                         <Typography variant="h5" sx={{ fontWeight: 'bold', mb: 2, color: '#1976D2' }}>
//                             1. Create New Quiz
//                         </Typography>
//                         <Box display="flex" gap={2}>
//                             <Input
//                                 fullWidth
//                                 type="text"
//                                 value={quizName}
//                                 onChange={(e) => setQuizName(e.target.value)}
//                                 placeholder="Enter Quiz Name (e.g. Science Quiz)"
//                                 sx={{ px: 2, py: 1, border: '1px solid #ccc', borderRadius: 1 }}
//                             />
//                             <Button onClick={handleCreateQuiz} variant="contained" sx={{ whiteSpace: 'nowrap' }}>
//                                 Create Quiz
//                             </Button>
//                         </Box>
//                     </CardContent>
//                 </Card>

//                 {/* Section 2: Select Quiz */}
//                 <Card sx={{ boxShadow: 3, borderRadius: 3 }}>
//                     <CardContent>
//                         <Typography variant="h5" sx={{ fontWeight: 'bold', mb: 2, color: '#1976D2' }}>
//                             2. Select Quiz to Edit
//                         </Typography>
//                         <FormControl fullWidth>
//                             <InputLabel>Select Quiz</InputLabel>
//                             <Select
//                                 value={selectedQuiz}
//                                 onChange={(e) => setSelectedQuiz(e.target.value)}
//                                 label="Select Quiz"
//                             >
//                                 <MenuItem value="" disabled>Select Quiz</MenuItem>
//                                 {quizzes.map((quiz) => (
//                                     <MenuItem key={quiz._id} value={quiz._id}>{quiz.name}</MenuItem>
//                                 ))}
//                             </Select>
//                         </FormControl>
//                     </CardContent>
//                 </Card>

//                 <Box display="flex" gap={4} flexDirection={{ xs: 'column', md: 'row' }}>
//                     {/* Section 3: Manual Approach */}
//                     <Card sx={{ flex: 1, boxShadow: 3, borderRadius: 3 }}>
//                         <CardContent>
//                             <Typography variant="h6" sx={{ fontWeight: 'bold', mb: 2, color: '#1976D2' }}>
//                                 Manual Approach
//                             </Typography>
//                             <FormControl fullWidth sx={{ mb: 2 }}>
//                                 <InputLabel>Question Type</InputLabel>
//                                 <Select
//                                     value={manualType}
//                                     onChange={(e) => handleSelectManualType(e.target.value)}
//                                     label="Question Type"
//                                 >
//                                     <MenuItem value="MCQs">MCQs</MenuItem>
//                                     <MenuItem value="True/False Questions">True/False</MenuItem>
//                                     <MenuItem value="Fill in the Blanks">Fill in the Blanks</MenuItem>
//                                 </Select>
//                             </FormControl>

//                             {manualQuestion && (
//                                 <Box sx={{ mt: 2, p: 2, bgcolor: '#f9f9f9', borderRadius: 2 }}>
//                                     <QuestionPrototype
//                                         type={manualType}
//                                         question={manualQuestion}
//                                         setQuestion={setManualQuestion}
//                                     />
//                                     <Button
//                                         fullWidth
//                                         variant="contained"
//                                         color="primary"
//                                         onClick={handleSaveManual}
//                                         sx={{ mt: 2 }}
//                                     >
//                                         Save Manual Question
//                                     </Button>
//                                 </Box>
//                             )}
//                         </CardContent>
//                     </Card>

//                     {/* Section 4: AI Approach */}
//                     <Card sx={{ flex: 1, boxShadow: 3, borderRadius: 3 }}>
//                         <CardContent>
//                             <Typography variant="h6" sx={{ fontWeight: 'bold', mb: 2, color: '#FF6F61' }}>
//                                 AI Generation (Mix of 5)
//                             </Typography>
//                             <Button
//                                 fullWidth
//                                 variant="contained"
//                                 color="secondary"
//                                 onClick={handleGenerateAI}
//                                 sx={{
//                                     background: 'linear-gradient(45deg, #FF6F61 30%, #FF9F94 90%)',
//                                     color: 'white',
//                                     mb: 2
//                                 }}
//                             >
//                                 Generate 5 Questions via AI
//                             </Button>

//                             {aiQuestions.length > 0 && (
//                                 <Box sx={{ mt: 2 }}>
//                                     <Typography variant="subtitle2" sx={{ mb: 1 }}>Generated Questions:</Typography>
//                                     <List dense sx={{ bgcolor: '#fff5f4', borderRadius: 2, maxHeight: 300, overflow: 'auto' }}>
//                                         {aiQuestions.map((q, i) => (
//                                             <React.Fragment key={i}>
//                                                 <ListItem>
//                                                     <ListItemText 
//                                                         primary={`${i+1}. ${q.questionText}`} 
//                                                         secondary={q.type}
//                                                     />
//                                                 </ListItem>
//                                                 {i < aiQuestions.length - 1 && <Divider />}
//                                             </React.Fragment>
//                                         ))}
//                                     </List>
//                                     <Button
//                                         fullWidth
//                                         variant="contained"
//                                         color="success"
//                                         onClick={handleSaveAI}
//                                         sx={{ mt: 2 }}
//                                     >
//                                         Save All AI Questions
//                                     </Button>
//                                 </Box>
//                             )}
//                         </CardContent>
//                     </Card>
//                 </Box>
//             </Box>
//         </Container>
//     );
// }

// export default CreateQuizPage;











'use client'

import React, { useContext, useEffect, useState } from 'react';
import { toast } from 'react-toastify';
import userContext from '@/context/userDetails/UserContext';
import QuestionPrototype from '@/app/components/QuestionPrototype';

// ─── Inline style constants ────────────────────────────────────────────────────
const CSS = `
  @import url('https://fonts.googleapis.com/css2?family=Sora:wght@400;600;700&family=DM+Sans:ital,wght@0,300;0,400;0,500;1,400&display=swap');

  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

  .cqp-root {
    font-family: 'DM Sans', sans-serif;
    min-height: 100vh;
    background: #F0F4FF;
    background-image:
      radial-gradient(circle at 15% 20%, rgba(99,102,241,0.12) 0%, transparent 50%),
      radial-gradient(circle at 85% 80%, rgba(245,158,11,0.10) 0%, transparent 50%);
    padding: 2.5rem 1rem 4rem;
  }

  .cqp-wrapper {
    max-width: 860px;
    margin: 0 auto;
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }

  /* ── Page header ── */
  .cqp-header {
    text-align: center;
    margin-bottom: 0.5rem;
  }
  .cqp-header h1 {
    font-family: 'Sora', sans-serif;
    font-size: clamp(1.6rem, 4vw, 2.2rem);
    font-weight: 700;
    color: #1E1B4B;
    letter-spacing: -0.03em;
  }
  .cqp-header p {
    margin-top: 0.35rem;
    font-size: 0.92rem;
    color: #6B7280;
    font-weight: 400;
  }

  /* ── Cards ── */
  .cqp-card {
    background: #ffffff;
    border-radius: 18px;
    border: 1px solid rgba(99,102,241,0.1);
    box-shadow: 0 2px 12px rgba(30,27,75,0.07), 0 0 0 0 transparent;
    padding: 1.75rem 2rem;
    transition: box-shadow 0.25s ease, transform 0.25s ease;
  }
  .cqp-card:hover {
    box-shadow: 0 6px 28px rgba(99,102,241,0.13);
    transform: translateY(-1px);
  }

  .cqp-card-label {
    display: inline-flex;
    align-items: center;
    gap: 0.45rem;
    font-family: 'Sora', sans-serif;
    font-size: 0.72rem;
    font-weight: 600;
    letter-spacing: 0.1em;
    text-transform: uppercase;
    color: #6366F1;
    background: #EEF2FF;
    padding: 0.28rem 0.75rem;
    border-radius: 99px;
    margin-bottom: 0.85rem;
  }

  .cqp-card-title {
    font-family: 'Sora', sans-serif;
    font-size: 1.15rem;
    font-weight: 700;
    color: #1E1B4B;
    margin-bottom: 1.1rem;
  }

  /* ── Input row ── */
  .cqp-input-row {
    display: flex;
    gap: 0.75rem;
    align-items: stretch;
  }
  @media (max-width: 520px) {
    .cqp-input-row { flex-direction: column; }
  }

  .cqp-input {
    flex: 1;
    height: 48px;
    padding: 0 1rem;
    border: 1.5px solid #E0E7FF;
    border-radius: 12px;
    font-family: 'DM Sans', sans-serif;
    font-size: 0.9rem;
    color: #1E1B4B;
    background: #F8F9FF;
    outline: none;
    transition: border-color 0.2s, box-shadow 0.2s;
  }
  .cqp-input:focus {
    border-color: #6366F1;
    box-shadow: 0 0 0 3px rgba(99,102,241,0.15);
    background: #fff;
  }
  .cqp-input::placeholder { color: #A5B4FC; }

  /* ── Buttons ── */
  .cqp-btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 0.45rem;
    height: 48px;
    padding: 0 1.4rem;
    border: none;
    border-radius: 12px;
    font-family: 'DM Sans', sans-serif;
    font-size: 0.88rem;
    font-weight: 600;
    cursor: pointer;
    white-space: nowrap;
    transition: filter 0.2s, transform 0.15s, box-shadow 0.2s;
  }
  .cqp-btn:active { transform: scale(0.97); }

  .cqp-btn-primary {
    background: linear-gradient(135deg, #6366F1 0%, #4F46E5 100%);
    color: #fff;
    box-shadow: 0 4px 14px rgba(99,102,241,0.35);
  }
  .cqp-btn-primary:hover { filter: brightness(1.1); box-shadow: 0 6px 20px rgba(99,102,241,0.45); }

  .cqp-btn-ai {
    background: linear-gradient(135deg, #F59E0B 0%, #EF4444 100%);
    color: #fff;
    width: 100%;
    box-shadow: 0 4px 14px rgba(245,158,11,0.35);
  }
  .cqp-btn-ai:hover { filter: brightness(1.08); box-shadow: 0 6px 20px rgba(245,158,11,0.45); }

  .cqp-btn-success {
    background: linear-gradient(135deg, #10B981 0%, #059669 100%);
    color: #fff;
    width: 100%;
    box-shadow: 0 4px 14px rgba(16,185,129,0.3);
  }
  .cqp-btn-success:hover { filter: brightness(1.08); }

  .cqp-btn-save {
    background: #6366F1;
    color: #fff;
    width: 100%;
    box-shadow: 0 4px 14px rgba(99,102,241,0.3);
  }
  .cqp-btn-save:hover { filter: brightness(1.1); }

  /* ── Select ── */
  .cqp-select {
    width: 100%;
    height: 48px;
    padding: 0 1rem;
    border: 1.5px solid #E0E7FF;
    border-radius: 12px;
    font-family: 'DM Sans', sans-serif;
    font-size: 0.9rem;
    color: #1E1B4B;
    background: #F8F9FF url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 20 20' fill='%236366F1'%3E%3Cpath fill-rule='evenodd' d='M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z' clip-rule='evenodd'/%3E%3C/svg%3E") no-repeat right 0.9rem center / 18px;
    appearance: none;
    -webkit-appearance: none;
    outline: none;
    cursor: pointer;
    transition: border-color 0.2s, box-shadow 0.2s;
  }
  .cqp-select:focus {
    border-color: #6366F1;
    box-shadow: 0 0 0 3px rgba(99,102,241,0.15);
    background-color: #fff;
  }

  /* ── Two-column approach grid ── */
  .cqp-approaches {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1.5rem;
  }
  @media (max-width: 640px) {
    .cqp-approaches { grid-template-columns: 1fr; }
  }

  /* ── AI card accent ── */
  .cqp-card-ai {
    border-color: rgba(245,158,11,0.2);
    background: linear-gradient(160deg, #fffdf5 0%, #fff 60%);
  }
  .cqp-card-label-ai {
    color: #D97706;
    background: #FEF3C7;
  }

  /* ── Question form area ── */
  .cqp-question-box {
    margin-top: 1rem;
    padding: 1.1rem;
    background: #F8F9FF;
    border-radius: 12px;
    border: 1px dashed #C7D2FE;
  }

  /* ── AI question list ── */
  .cqp-ai-list {
    margin-top: 0.85rem;
    background: #FFFBF2;
    border: 1px solid #FDE68A;
    border-radius: 12px;
    overflow: hidden;
    max-height: 280px;
    overflow-y: auto;
  }
  .cqp-ai-list-item {
    display: flex;
    gap: 0.75rem;
    align-items: flex-start;
    padding: 0.75rem 1rem;
    border-bottom: 1px solid #FDE68A;
    transition: background 0.15s;
  }
  .cqp-ai-list-item:last-child { border-bottom: none; }
  .cqp-ai-list-item:hover { background: #FEF9EC; }

  .cqp-ai-badge {
    flex-shrink: 0;
    width: 22px;
    height: 22px;
    background: #F59E0B;
    color: #fff;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 0.7rem;
    font-weight: 700;
    font-family: 'Sora', sans-serif;
    margin-top: 1px;
  }
  .cqp-ai-q-text {
    font-size: 0.86rem;
    color: #374151;
    line-height: 1.45;
  }
  .cqp-ai-q-type {
    display: inline-block;
    margin-top: 0.2rem;
    font-size: 0.72rem;
    font-weight: 600;
    color: #D97706;
    background: #FEF3C7;
    padding: 0.1rem 0.5rem;
    border-radius: 99px;
  }

  /* ── Scrollbar ── */
  .cqp-ai-list::-webkit-scrollbar { width: 4px; }
  .cqp-ai-list::-webkit-scrollbar-track { background: transparent; }
  .cqp-ai-list::-webkit-scrollbar-thumb { background: #FCD34D; border-radius: 99px; }

  /* ── Step badge on cards ── */
  .cqp-step-badge {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 26px;
    height: 26px;
    background: #6366F1;
    color: #fff;
    border-radius: 8px;
    font-family: 'Sora', sans-serif;
    font-size: 0.78rem;
    font-weight: 700;
    margin-right: 0.55rem;
    flex-shrink: 0;
  }
  .cqp-card-title-row {
    display: flex;
    align-items: center;
    margin-bottom: 1.1rem;
  }
`;

function CreateQuizPage() {
    const context = useContext(userContext);
    const { user } = context;
    const [quizzes, setQuizzes] = useState([]);
    const [selectedQuiz, setSelectedQuiz] = useState('');
    const [quizName, setQuizName] = useState('');

    const [manualType, setManualType] = useState('');
    const [manualQuestion, setManualQuestion] = useState(null);

    const [aiQuestions, setAiQuestions] = useState([]);

    const myID = user?._id;

    useEffect(() => {
        const fetchQuizzes = async () => {
            try {
                const response = await fetch('/api/getquiz');
                if (!response.ok) throw new Error('Network response was not ok');
                const data = await response.json();
                setQuizzes(data);
            } catch (error) {
                console.error('Failed to fetch quizzes:', error);
            }
        };
        fetchQuizzes();
    }, [myID]);

    const handleCreateQuiz = async () => {
        if (!quizName) { toast.warning('Please provide a name for the quiz.'); return; }
        const response = await fetch('/api/quiz', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ name: quizName, userId: myID }),
        });
        if (response.ok) {
            const data = await response.json();
            setQuizzes([...quizzes, data.quiz]);
            setQuizName('');
            toast.success('Quiz Created Successfully');
        } else {
            toast.warning('Failed to create quiz.');
        }
    };

    const handleSelectManualType = (type) => {
        setManualType(type);
        setManualQuestion(
            type === 'MCQs' ? { questionText: '', options: ['', '', '', ''], correctOption: 0 } :
            type === 'True/False Questions' ? { questionText: '', correctOption: true } :
            { questionText: '', correctAnswer: '' }
        );
    };

    const handleSaveManual = async () => {
        if (!selectedQuiz || !manualType || !manualQuestion) {
            toast.error('Please select a quiz and enter question details.'); return;
        }
        const response = await fetch('/api/questions', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ quizId: selectedQuiz, type: manualType, ...manualQuestion }),
        });
        if (response.ok) {
            setManualQuestion(null); setManualType('');
            toast.success('Manual question saved successfully!');
        } else {
            toast.error('Failed to save manual question.');
        }
    };

    const handleGenerateAI = async () => {
        if (!selectedQuiz) { toast.error('Please select a quiz first'); return; }
        const selectedQuizData = quizzes.find(q => q._id === selectedQuiz);
        const inputText = selectedQuizData ? selectedQuizData.name : '';
        toast.info('Generating 5 AI questions… please wait.');
        const response = await fetch('/api/generate', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ inputText, quizId: selectedQuiz }),
        });
        const result = await response.json();
        if (response.ok) {
            setAiQuestions(result.quizQuestions || []);
            toast.success('5 Questions generated by AI!');
        } else {
            toast.error('Failed to generate questions.');
        }
    };

    const handleSaveAI = async () => {
        if (!selectedQuiz || !aiQuestions.length) { toast.error('No AI questions to save.'); return; }
        let successCount = 0;
        for (let q of aiQuestions) {
            const response = await fetch('/api/questions', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ quizId: selectedQuiz, ...q }),
            });
            if (response.ok) successCount++;
        }
        if (successCount === aiQuestions.length) {
            toast.success(`Successfully saved all ${successCount} AI questions!`);
            setAiQuestions([]);
        } else {
            toast.warning(`Saved ${successCount} out of ${aiQuestions.length} questions.`);
        }
    };

    return (
        <>
            <style>{CSS}</style>
            <div className="cqp-root">
                <div className="cqp-wrapper">

                    {/* ── Header ── */}
                    <header className="cqp-header">
                        <h1>Quiz Builder</h1>
                        <p>Create a quiz, add questions manually, or let AI do the heavy lifting.</p>
                    </header>

                    {/* ── Step 1: Create Quiz ── */}
                    <div className="cqp-card">
                        <div className="cqp-card-title-row">
                            <span className="cqp-step-badge">1</span>
                            <span className="cqp-card-title" style={{ marginBottom: 0 }}>Create a New Quiz</span>
                        </div>
                        <div className="cqp-input-row">
                            <input
                                className="cqp-input"
                                type="text"
                                value={quizName}
                                onChange={(e) => setQuizName(e.target.value)}
                                placeholder="e.g. Science Quiz — Chapter 4"
                                onKeyDown={(e) => e.key === 'Enter' && handleCreateQuiz()}
                            />
                            <button className="cqp-btn cqp-btn-primary" onClick={handleCreateQuiz}>
                                <svg width="15" height="15" viewBox="0 0 20 20" fill="none"><path d="M10 4v12M4 10h12" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></svg>
                                Create Quiz
                            </button>
                        </div>
                    </div>

                    {/* ── Step 2: Select Quiz ── */}
                    <div className="cqp-card">
                        <div className="cqp-card-title-row">
                            <span className="cqp-step-badge">2</span>
                            <span className="cqp-card-title" style={{ marginBottom: 0 }}>Select Quiz to Edit</span>
                        </div>
                        <select
                            className="cqp-select"
                            value={selectedQuiz}
                            onChange={(e) => setSelectedQuiz(e.target.value)}
                        >
                            <option value="" disabled>— Choose a quiz —</option>
                            {quizzes.map((quiz) => (
                                <option key={quiz._id} value={quiz._id}>{quiz.name}</option>
                            ))}
                        </select>
                    </div>

                    {/* ── Step 3: Add Questions ── */}
                    <div className="cqp-approaches">

                        {/* Manual */}
                        <div className="cqp-card">
                            <div className="cqp-card-label">
                                <svg width="12" height="12" viewBox="0 0 20 20" fill="currentColor"><path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"/></svg>
                                Manual
                            </div>
                            <div className="cqp-card-title">Write a Question</div>
                            <select
                                className="cqp-select"
                                value={manualType}
                                onChange={(e) => handleSelectManualType(e.target.value)}
                            >
                                <option value="" disabled>Select question type</option>
                                <option value="MCQs">Multiple Choice (MCQ)</option>
                                <option value="True/False Questions">True / False</option>
                                <option value="Fill in the Blanks">Fill in the Blank</option>
                            </select>

                            {manualQuestion && (
                                <div className="cqp-question-box">
                                    <QuestionPrototype
                                        type={manualType}
                                        question={manualQuestion}
                                        setQuestion={setManualQuestion}
                                    />
                                    <button className="cqp-btn cqp-btn-save" style={{ marginTop: '0.85rem' }} onClick={handleSaveManual}>
                                        Save Question
                                    </button>
                                </div>
                            )}
                        </div>

                        {/* AI */}
                        <div className="cqp-card cqp-card-ai">
                            <div className="cqp-card-label cqp-card-label-ai">
                                <svg width="12" height="12" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M11.3 1.046A1 1 0 0112 2v5h4a1 1 0 01.82 1.573l-7 10A1 1 0 018 18v-5H4a1 1 0 01-.82-1.573l7-10a1 1 0 011.12-.38z" clipRule="evenodd"/></svg>
                                AI Generation
                            </div>
                            <div className="cqp-card-title">Generate 5 Questions</div>
                            <button className="cqp-btn cqp-btn-ai" onClick={handleGenerateAI}>
                                <svg width="15" height="15" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M11.3 1.046A1 1 0 0112 2v5h4a1 1 0 01.82 1.573l-7 10A1 1 0 018 18v-5H4a1 1 0 01-.82-1.573l7-10a1 1 0 011.12-.38z" clipRule="evenodd"/></svg>
                                Generate via AI
                            </button>

                            {aiQuestions.length > 0 && (
                                <>
                                    <div className="cqp-ai-list">
                                        {aiQuestions.map((q, i) => (
                                            <div key={i} className="cqp-ai-list-item">
                                                <span className="cqp-ai-badge">{i + 1}</span>
                                                <div>
                                                    <div className="cqp-ai-q-text">{q.questionText}</div>
                                                    <span className="cqp-ai-q-type">{q.type}</span>
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                    <button className="cqp-btn cqp-btn-success" style={{ marginTop: '0.85rem' }} onClick={handleSaveAI}>
                                        Save All AI Questions
                                    </button>
                                </>
                            )}
                        </div>
                    </div>

                </div>
            </div>
        </>
    );
}

export default CreateQuizPage;