'use client'

import React, { useContext, useEffect, useState } from 'react';
import { Container, Typography, FormControl, InputLabel, Select, MenuItem, Button, Box, Card, CardContent, Input, List, ListItem, ListItemText, Divider } from '@mui/material';
import { toast } from 'react-toastify';
import userContext from '@/context/userDetails/UserContext';
import QuestionPrototype from '@/app/components/QuestionPrototype';

function CreateQuizPage() {
    const context = useContext(userContext);
    const { user } = context;
    const [quizzes, setQuizzes] = useState([]);
    const [selectedQuiz, setSelectedQuiz] = useState('');
    const [quizName, setQuizName] = useState('');
    
    // Manual Question State
    const [manualType, setManualType] = useState('');
    const [manualQuestion, setManualQuestion] = useState(null);

    // AI Question State
    const [aiQuestions, setAiQuestions] = useState([]);
    
    const myID = user?._id;

    useEffect(() => {
        const fetchQuizzes = async () => {
            try {
                const response = await fetch('/api/getquiz');
                if (!response.ok) throw new Error('Network response was not ok');
                const data = await response.json();
                setQuizzes(data);
            } catch (error) {
                console.error('Failed to fetch quizzes:', error);
            }
        };
        fetchQuizzes();
    }, [myID]);

    const handleCreateQuiz = async () => {
        if (!quizName) {
            toast.warning('Please provide a name for the quiz.');
            return;
        }
        const response = await fetch('/api/quiz', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ name: quizName, userId: myID }),
        });
        if (response.ok) {
            const data = await response.json();
            setQuizzes([...quizzes, data.quiz]);
            setQuizName('');
            toast.success("Quiz Created Successfully");
        } else {
            toast.warning('Failed to create quiz.');
        }
    };

    const handleSelectManualType = (type) => {
        setManualType(type);
        setManualQuestion(
            type === 'MCQs' ? { questionText: '', options: ['', '', '', ''], correctOption: 0 } :
            type === 'True/False Questions' ? { questionText: '', correctOption: true } :
            { questionText: '', correctAnswer: '' }
        );
    };

    const handleSaveManual = async () => {
        if (!selectedQuiz || !manualType || !manualQuestion) {
            toast.error('Please select a quiz and enter question details.');
            return;
        }

        const response = await fetch('/api/questions', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ quizId: selectedQuiz, type: manualType, ...manualQuestion }),
        });

        if (response.ok) {
            setManualQuestion(null);
            setManualType('');
            toast.success('Manual question saved successfully!');
        } else {
            toast.error('Failed to save manual question.');
        }
    };

    const handleGenerateAI = async () => {
        if (!selectedQuiz) {
            toast.error('Please select a quiz first');
            return;
        }

        const selectedQuizData = quizzes.find(q => q._id === selectedQuiz);
        const inputText = selectedQuizData ? selectedQuizData.name : '';

        toast.info("Generating 5 AI questions... please wait.");

        const response = await fetch('/api/generate', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ inputText, quizId: selectedQuiz }),
        });

        const result = await response.json();

        if (response.ok) {
            setAiQuestions(result.quizQuestions || []);
            toast.success("5 Questions generated by AI!");
        } else {
            console.error('Failed to generate questions:', result.error);
            toast.error('Failed to generate questions.');
        }
    };

    const handleSaveAI = async () => {
        if (!selectedQuiz || !aiQuestions.length) {
            toast.error('No AI questions to save.');
            return;
        }

        let successCount = 0;
        for (let q of aiQuestions) {
            const response = await fetch('/api/questions', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ quizId: selectedQuiz, ...q }),
            });
            if (response.ok) successCount++;
        }

        if (successCount === aiQuestions.length) {
            toast.success(`Successfully saved all ${successCount} AI questions!`);
            setAiQuestions([]);
        } else {
            toast.warning(`Saved ${successCount} out of ${aiQuestions.length} questions.`);
        }
    };

    return (
        <Container maxWidth="md" sx={{ py: 4 }}>
            <Box display="flex" flexDirection="column" gap={4}>
                {/* Section 1: Create Quiz */}
                <Card sx={{ boxShadow: 3, borderRadius: 3 }}>
                    <CardContent>
                        <Typography variant="h5" sx={{ fontWeight: 'bold', mb: 2, color: '#1976D2' }}>
                            1. Create New Quiz
                        </Typography>
                        <Box display="flex" gap={2}>
                            <Input
                                fullWidth
                                type="text"
                                value={quizName}
                                onChange={(e) => setQuizName(e.target.value)}
                                placeholder="Enter Quiz Name (e.g. Science Quiz)"
                                sx={{ px: 2, py: 1, border: '1px solid #ccc', borderRadius: 1 }}
                            />
                            <Button onClick={handleCreateQuiz} variant="contained" sx={{ whiteSpace: 'nowrap' }}>
                                Create Quiz
                            </Button>
                        </Box>
                    </CardContent>
                </Card>

                {/* Section 2: Select Quiz */}
                <Card sx={{ boxShadow: 3, borderRadius: 3 }}>
                    <CardContent>
                        <Typography variant="h5" sx={{ fontWeight: 'bold', mb: 2, color: '#1976D2' }}>
                            2. Select Quiz to Edit
                        </Typography>
                        <FormControl fullWidth>
                            <InputLabel>Select Quiz</InputLabel>
                            <Select
                                value={selectedQuiz}
                                onChange={(e) => setSelectedQuiz(e.target.value)}
                                label="Select Quiz"
                            >
                                <MenuItem value="" disabled>Select Quiz</MenuItem>
                                {quizzes.map((quiz) => (
                                    <MenuItem key={quiz._id} value={quiz._id}>{quiz.name}</MenuItem>
                                ))}
                            </Select>
                        </FormControl>
                    </CardContent>
                </Card>

                <Box display="flex" gap={4} flexDirection={{ xs: 'column', md: 'row' }}>
                    {/* Section 3: Manual Approach */}
                    <Card sx={{ flex: 1, boxShadow: 3, borderRadius: 3 }}>
                        <CardContent>
                            <Typography variant="h6" sx={{ fontWeight: 'bold', mb: 2, color: '#1976D2' }}>
                                Manual Approach
                            </Typography>
                            <FormControl fullWidth sx={{ mb: 2 }}>
                                <InputLabel>Question Type</InputLabel>
                                <Select
                                    value={manualType}
                                    onChange={(e) => handleSelectManualType(e.target.value)}
                                    label="Question Type"
                                >
                                    <MenuItem value="MCQs">MCQs</MenuItem>
                                    <MenuItem value="True/False Questions">True/False</MenuItem>
                                    <MenuItem value="Fill in the Blanks">Fill in the Blanks</MenuItem>
                                </Select>
                            </FormControl>

                            {manualQuestion && (
                                <Box sx={{ mt: 2, p: 2, bgcolor: '#f9f9f9', borderRadius: 2 }}>
                                    <QuestionPrototype
                                        type={manualType}
                                        question={manualQuestion}
                                        setQuestion={setManualQuestion}
                                    />
                                    <Button
                                        fullWidth
                                        variant="contained"
                                        color="primary"
                                        onClick={handleSaveManual}
                                        sx={{ mt: 2 }}
                                    >
                                        Save Manual Question
                                    </Button>
                                </Box>
                            )}
                        </CardContent>
                    </Card>

                    {/* Section 4: AI Approach */}
                    <Card sx={{ flex: 1, boxShadow: 3, borderRadius: 3 }}>
                        <CardContent>
                            <Typography variant="h6" sx={{ fontWeight: 'bold', mb: 2, color: '#FF6F61' }}>
                                AI Generation (Mix of 5)
                            </Typography>
                            <Button
                                fullWidth
                                variant="contained"
                                color="secondary"
                                onClick={handleGenerateAI}
                                sx={{
                                    background: 'linear-gradient(45deg, #FF6F61 30%, #FF9F94 90%)',
                                    color: 'white',
                                    mb: 2
                                }}
                            >
                                Generate 5 Questions via AI
                            </Button>

                            {aiQuestions.length > 0 && (
                                <Box sx={{ mt: 2 }}>
                                    <Typography variant="subtitle2" sx={{ mb: 1 }}>Generated Questions:</Typography>
                                    <List dense sx={{ bgcolor: '#fff5f4', borderRadius: 2, maxHeight: 300, overflow: 'auto' }}>
                                        {aiQuestions.map((q, i) => (
                                            <React.Fragment key={i}>
                                                <ListItem>
                                                    <ListItemText 
                                                        primary={`${i+1}. ${q.questionText}`} 
                                                        secondary={q.type}
                                                    />
                                                </ListItem>
                                                {i < aiQuestions.length - 1 && <Divider />}
                                            </React.Fragment>
                                        ))}
                                    </List>
                                    <Button
                                        fullWidth
                                        variant="contained"
                                        color="success"
                                        onClick={handleSaveAI}
                                        sx={{ mt: 2 }}
                                    >
                                        Save All AI Questions
                                    </Button>
                                </Box>
                            )}
                        </CardContent>
                    </Card>
                </Box>
            </Box>
        </Container>
    );
}

export default CreateQuizPage;
